BeatThePokémon/Controllers/GevechtController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ModelLibrary.Models;
using BeatThePokemon.Models.Convert;
using BeatThePokemon.Models.ViewModels;
using BeatThePokemon.Repos;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BeatThePokémon.Controllers
{
    public class GevechtController : Controller
    {
        private AccountRepo accountRepo;
        private GevechtRepo gevechtRepo;
        private AanvalRepo aanvalRepo;

        public GevechtController(AccountRepo acrepo, GevechtRepo grepo, AanvalRepo anrepo)
        {
            this.accountRepo = acrepo;
            this.gevechtRepo = grepo;
            this.aanvalRepo = anrepo;
        }

        [HttpGet]
        public IActionResult Index(GevechtViewModel gvm)
        {
            if (HttpContext.Session.GetInt32("AccountID") == null) { return RedirectToAction("Login", "Account"); }

            int userId = (int)HttpContext.Session.GetInt32("AccountID");            

            if (!accountRepo.HasPokemon(userId))
            {
                return RedirectToAction("NewGame", "Home");
            }

            if (!gevechtRepo.GevechtExists(userId))
            {
                gevechtRepo.CreateGevecht(accountRepo.GetUserById(userId));
            }

            Pokemon GebruikerPokemon = gevechtRepo.GetGebruikerPokemonByTeamId(gevechtRepo.GetGebruikerTeamId(userId));
            Pokemon TegenstanderPokemon = gevechtRepo.GetTegenstanderPokemonByTeamId(gevechtRepo.GetTegenstanderTeamId(userId));
            gvm.GebruikerPokemon = PokemonViewModelConvert.PokemonToPokemonViewModel(GebruikerPokemon);
            gvm.TegenstanderPokemon = PokemonViewModelConvert.PokemonToPokemonViewModel(TegenstanderPokemon);

            gvm = GevechtConvert.ImageConvert(gvm);

            return View("Index", gvm);
        }

        [HttpGet]
        public IActionResult Aanvallen(int pokId)
        {
            if (HttpContext.Session.GetInt32("AccountID") == null) { return RedirectToAction("Login", "Account"); }

            AanvallenGevechtViewModel agvm = new AanvallenGevechtViewModel();
            agvm.Aanvallen = AanvalViewModelConvert.AanvalListToViewModelList(aanvalRepo.GetAllByPokemon(pokId));

            return View(agvm);
        }

        [HttpPost]
        public IActionResult VoerAanvalUit(int gAanvalId)
        {
            Account a = accountRepo.GetUserById((int)HttpContext.Session.GetInt32("AccountID"));
            int tegenstanderTeamId = gevechtRepo.GetTegenstanderTeamId(a.Id);
            int gebruikerTeamId = gevechtRepo.GetGebruikerTeamId(a.Id);

            int gOudeHp = gevechtRepo.GetGebruikerPokemonByTeamId(gebruikerTeamId).HP;
            int tOudeHp = gevechtRepo.GetTegenstanderPokemonByTeamId(tegenstanderTeamId).HP;

            Aanval gAanval = gevechtRepo.VoerGebruikerAanvalUit(gAanvalId, tegenstanderTeamId, tOudeHp);
            Aanval tAanval = gevechtRepo.VoerTegenstanderAanvalUit(gebruikerTeamId, gOudeHp, tegenstanderTeamId);

            GevechtViewModel gvm = new GevechtViewModel();
            gvm.GebruikerAanval = AanvalViewModelConvert.AanvalToViewModel(gAanval);
            gvm.TegenstanderAanval = AanvalViewModelConvert.AanvalToViewModel(tAanval);
            gvm.OudGebruikerHp = gOudeHp;
            gvm.OudtegenstanderHp = tOudeHp;

            return Index(gvm);
        }

        [HttpPost]
        public IActionResult NewGevecht()
        {
            Account a = accountRepo.GetUserById((int)HttpContext.Session.GetInt32("AccountID"));
            gevechtRepo.StartNewGevecht(a.Id);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult NewGame()
        {
            Account a = accountRepo.GetUserById((int)HttpContext.Session.GetInt32("AccountID"));
            gevechtRepo.StartNewGame(a.Id);

            return RedirectToAction("Index");
        }
    }
}

BeatThePokémon/Controllers/PokemonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BeatThePokemon.Context.MSSQL;
using ModelLibrary.Models;
using BeatThePokemon.Models.Convert;
using BeatThePokemon.Models.ViewModels;
using BeatThePokemon.Repos;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BeatThePokemon.Controllers
{
    public class PokemonController : Controller
    {
        private PokemonRepo pokemonRepo;
        private SoortRepo soortRepo;
        private AanvalRepo aanvalRepo;

        public PokemonController(PokemonRepo pRepo, SoortRepo sRepo, AanvalRepo aRepo)
        {
            this.pokemonRepo = pRepo;
            this.soortRepo = sRepo;
            this.aanvalRepo = aRepo;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreatePokemon()
        {
            if (HttpContext.Session.GetInt32("AccountID") == null) { return RedirectToAction("Login", "Account"); }

            PokemonCreateViewModel pcvm = new PokemonCreateViewModel();
            pcvm.AlleSoorten = SoortViewModelConvert.SoortListToViewModelList(soortRepo.GetAll());
            return View(pcvm);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreatePokemon(PokemonCreateViewModel pcvm)
        {
            if (ModelState.IsValid)
            {
                PokemonCreateConvert pcc = new PokemonCreateConvert();
                pcvm.ToeTeVoegenAanval = AanvalViewModelConvert.AanvalToViewModel(aanvalRepo.GetByName(pcvm.NaamAanval));
                Pokemon p = pcc.CreateToPokemon(pcvm);
                pokemonRepo.Create(p);
                return RedirectToAction("AllePokemon");
            }
            pcvm.AlleSoorten = SoortViewModelConvert.SoortListToViewModelList(soortRepo.GetAll());
            return View(pcvm);
        }

        [HttpGet]
        public IActionResult CreateAanval()
        {
            if (HttpContext.Session.GetInt32("AccountID") == null) { return RedirectToAction("Login", "Account"); }

            AanvalCreateViewModel acvm = new AanvalCreateViewModel();
            acvm.AlleSoorten = SoortViewModelConvert.SoortListToViewModelList(soortRepo.GetAll());
            return View(acvm);
        }

        [HttpPost]
        public IActionResult CreateAanval(AanvalCreateViewModel acvm)
        {
            AanvalCreateConvert acc = new AanvalCreateConvert();
            aanvalRepo.Create(acc.CreateToAanval(acvm));
            acvm.AlleSoorten = SoortViewModelConvert.SoortListToViewModelList(soortRepo.GetAll());
            return View(acvm);
        }

        [HttpGet]
        public IActionResult AllePokemon()
        {
            if (HttpContext.Session.GetInt32("AccountID") == null) { return RedirectToAction("Login", "Account"); }

            AllePokemonConvert pvc = new AllePokemonConvert();
            AllePokemonViewModel apvm = pvc.PokemonToView(pokemonRepo.GetAll());
            return View(apvm);
        }

        [HttpPost]
        public IActionResult Delete(AllePokemonViewModel apvm)
        {
            pokemonRepo.Delete(apvm.Id);
            return RedirectToAction("AllePokemon");
        }

        public IActionResult Aanvallen(string term)
        {
            List<Aanval> aanvallen = aanvalRepo.GetAll();

            List<string> returnList = new List<string>();
            foreach (Aanval s in aanvallen)
            {
                if (s.Naam.StartsWith(term))
                {
                    returnList.Add(s.Naam);
                }
            }

            return Json(returnList);
        }
    }
}

BeatThePokémon/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeatThePokemon</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
    <header>
        <div class="hover-slidedown container-fluid">
            <nav class="navbar blue">
                <div class="logo-container">
                </div>
                <label class="username">@Context.Session.GetString("Gebruikernaam")</label>
            </nav>
            <div class="nav-transformation blue container-fluid">
                <table class="nav-table">
                    <tr>
                        <th valign="top"><a class="nav-text" asp-controller="Home" asp-action="Index">Home</a></th>
                        @if (Context.Session.GetString("Gebruikersnaam") == null)
                        {
                            <th valign="top"><a class="nav-text" asp-controller="Account" asp-action="Login">Login</a></th>
                        }
                        else
                        {
                            <th valign="top"><a class="nav-text" asp-controller="Account" asp-action="LogOut">Logout</a></th>
                        }
                        <th valign="top"><a class="nav-text" asp-controller="Gevecht" asp-action="Index">Gevecht</a></th>
                        <th valign="top">
                            <div class="poke-nav-btn">
                                <a class="nav-text">Pokémon</a>
                                <div class="poke-dropdown-div">
                                    <a class="nav-text" asp-controller="Pokemon" asp-action="Create">Create</a>
                                    <br />
                                    <a class="nav-text" asp-controller="Pokemon" asp-action="AllePokemon">View</a>
                                </div>
                            </div>
                        </th>
                    </tr>
                </table>
            </div>
        </div>
    </header>


    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>